# imagen python
FROM python:3.11-slim

# directorio de trabajo
WORKDIR /app

# instalar requerimentos
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# copiar lo demas archivos
COPY . .

# puerto para ejecución de flask
EXPOSE 5000

# comando de ejecucion:primero arranca el back, luego espera 3 segundos, luego ejecuta los test y finallmente queda esperando
CMD ["sh", "-c", "python app.py & sleep 3 && python test.py && wait"]